version: "3"
services:
  strapi:
    image: strapi/strapi:alpine
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: "false"
    restart: unless-stopped
    volumes:
      - ./backend/app:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
