name: deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install
      - name: Generate build
        working-directory: ./frontend
        env:
          CI: false
        run: yarn build
      - name: Share artifact inside
        uses: actions/upload-artifact@v1
        with:
          name: mart
          path: ./frontend/build

  deploy-be:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) || github.event_name == 'push' }}
    steps:
      - name: SSH and deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/ppl/m-art-web
            git pull origin master
            make deploy-down
            make deploy

  deploy-fe:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build
        uses: actions/download-artifact@v1
        with:
          name: mart
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: mart/
          remote_path: /home/ppl/mart/
          remote_host: byeol.my.id
          remote_user: ppl
          remote_key: ${{ secrets.SSH_KEY }}
